# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AMapExtension
                                 A QGIS plugin
 This plugin utilizes the AMap (GaoDe Map) online service to provide navigation, POI queries, and district search.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-09-03
        copyright            : (C) 2025 by phoenix-gis
        email                : phoenixgis@sina.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AMapExtension class from file AMapExtension.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .amap_extension import AMapExtension
    return AMapExtension(iface)
